/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/send-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/telegram-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["telegramLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTicketsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/tickets/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQuestionsByTicket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/start-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startTicketExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/start-marathon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startMarathon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitExamAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExamSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExamHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPracticeSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitPracticeAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCategoryPerformance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSubscriptionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["cancelSubscription"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/payme/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["paymeWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/click/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["clickWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/announcements/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActiveAnnouncements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetQuestions"];
        put?: never;
        post: operations["adminCreateQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["adminUpdateQuestion"];
        post?: never;
        delete: operations["adminSoftDeleteQuestion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions/{id}/permanent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["adminPermanentDeleteQuestion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["adminToggleQuestionStatus"];
        trace?: never;
    };
    "/admin/questions/bulk-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["adminBulkToggleStatus"];
        trace?: never;
    };
    "/admin/questions/bulk-import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminBulkImportQuestions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions/export-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminExportTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetPlans"];
        put?: never;
        post: operations["adminCreatePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["adminUpdatePlan"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/plans/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["adminTogglePlanStatus"];
        trace?: never;
    };
    "/admin/payments/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payments/revenue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetRevenue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payments/revenue/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminExportRevenue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/exam-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetExamTemplates"];
        put?: never;
        post: operations["adminCreateExamTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/exam-templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["adminUpdateExamTemplate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reports/users/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminExportUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reports/exams/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminExportExams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reports/questions/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminExportQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["adminUpdateSetting"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetUserDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["adminUpdateUserRole"];
        trace?: never;
    };
    "/admin/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["adminUpdateUserStatus"];
        trace?: never;
    };
    "/admin/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetAnnouncements"];
        put?: never;
        post: operations["adminCreateAnnouncement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/announcements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["adminUpdateAnnouncement"];
        post?: never;
        delete: operations["adminDeleteAnnouncement"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LocalizedText: {
            /** @description Uzbek Cyrillic */
            uz: string;
            /** @description Uzbek Latin */
            uzLatin: string;
            /** @description Russian */
            ru: string;
        };
        PaginationMeta: {
            page: number;
            pageSize: number;
            totalCount: number;
            totalPages: number;
        };
        ApiError: {
            code: string;
            message: string;
        };
        ApiResponse: {
            success: boolean;
            data?: unknown;
            error?: components["schemas"]["ApiError"];
        };
        SendOtpRequest: {
            phoneNumber: string;
        };
        SendOtpResponse: {
            expiresInSeconds: number;
            retryAfterSeconds: number;
        };
        VerifyOtpRequest: {
            phoneNumber: string;
            code: string;
        };
        AuthResponse: {
            accessToken: string;
            refreshToken: string;
            /** @description Unix timestamp */
            expiresAt: number;
            user: components["schemas"]["UserDto"];
        };
        TelegramLoginRequest: {
            /** Format: int64 */
            id: number;
            firstName: string;
            lastName?: string | null;
            username?: string | null;
            photoUrl?: string | null;
            authDate: number;
            hash: string;
        };
        RefreshTokenRequest: {
            refreshToken: string;
        };
        UserDto: {
            /** Format: uuid */
            id: string;
            phoneNumber: string | null;
            firstName?: string | null;
            lastName?: string | null;
            /** @enum {string} */
            role: "user" | "admin";
            /** @enum {string} */
            subscriptionStatus: "none" | "active" | "expired" | "cancelled";
            /** @enum {string} */
            preferredLanguage: "uz" | "uzLatin" | "ru";
            /** Format: date-time */
            createdAt: string;
        };
        TicketDto: {
            ticketNumber: number;
            questionCount: number;
        };
        CategoryTreeDto: {
            /** Format: uuid */
            id: string;
            name: components["schemas"]["LocalizedText"];
            description: components["schemas"]["LocalizedText"];
            iconUrl?: string | null;
            questionCount: number;
            children?: components["schemas"]["CategoryTreeDto"][];
        };
        AnswerOptionDto: {
            /** Format: uuid */
            id: string;
            text: components["schemas"]["LocalizedText"];
            imageUrl?: string | null;
        };
        QuestionDto: {
            /** Format: uuid */
            id: string;
            text: components["schemas"]["LocalizedText"];
            imageUrl?: string | null;
            /** @enum {integer} */
            difficulty: 1 | 2 | 3;
            /** Format: uuid */
            categoryId: string;
            categoryName: components["schemas"]["LocalizedText"];
            ticketNumber: number;
            answerOptions: components["schemas"]["AnswerOptionDto"][];
        };
        StartExamRequest: {
            /** Format: uuid */
            templateId?: string | null;
            /** @enum {string} */
            licenseCategory: "AB" | "CD";
        };
        ExamQuestionDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            questionId: string;
            order: number;
            text: components["schemas"]["LocalizedText"];
            imageUrl?: string | null;
            answerOptions: components["schemas"]["AnswerOptionDto"][];
        };
        ExamSessionDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "inProgress" | "completed" | "expired";
            totalQuestions: number;
            passingScore: number;
            timeLimitMinutes: number;
            /**
             * Format: date-time
             * @description Null for marathon mode (no timer)
             */
            expiresAt?: string | null;
            /** @enum {string} */
            mode: "exam" | "ticket" | "marathon";
            ticketNumber?: number | null;
            questions: components["schemas"]["ExamQuestionDto"][];
        };
        SubmitAnswerRequest: {
            /** Format: uuid */
            sessionQuestionId: string;
            /** Format: uuid */
            selectedAnswerId: string;
            timeSpentSeconds?: number | null;
        };
        SubmitAnswerResponse: {
            recorded: boolean;
            answeredCount: number;
            totalCount: number;
        };
        ExamResultQuestionDto: {
            /** Format: uuid */
            questionId: string;
            text: components["schemas"]["LocalizedText"];
            imageUrl?: string | null;
            /** Format: uuid */
            selectedAnswerId: string | null;
            /** Format: uuid */
            correctAnswerId: string;
            isCorrect: boolean;
            explanation?: components["schemas"]["LocalizedText"];
            timeSpentSeconds?: number | null;
        };
        ExamResultDto: {
            /** Format: uuid */
            examId: string;
            score: number;
            correctAnswers: number;
            totalQuestions: number;
            passingScore: number;
            passed: boolean;
            timeTakenSeconds: number;
            /** Format: date-time */
            completedAt: string;
            questions: components["schemas"]["ExamResultQuestionDto"][];
        };
        ExamHistoryItemDto: {
            /** Format: uuid */
            examId: string;
            score: number;
            totalQuestions: number;
            passed: boolean;
            /** Format: date-time */
            completedAt: string;
            timeTakenSeconds: number;
        };
        PracticeQuestionDto: {
            /** Format: uuid */
            id: string;
            text: components["schemas"]["LocalizedText"];
            imageUrl?: string | null;
            categoryName: components["schemas"]["LocalizedText"];
            /** @enum {integer} */
            difficulty: 1 | 2 | 3;
            answerOptions: components["schemas"]["AnswerOptionDto"][];
            leitnerBox: number;
        };
        PracticeSessionDto: {
            questions: components["schemas"]["PracticeQuestionDto"][];
            dueReviewCount: number;
        };
        SubmitPracticeAnswerRequest: {
            /** Format: uuid */
            questionId: string;
            /** Format: uuid */
            selectedAnswerId: string;
            timeSpentSeconds?: number | null;
        };
        PracticeAnswerResultDto: {
            isCorrect: boolean;
            /** Format: uuid */
            correctAnswerId: string;
            explanation: components["schemas"]["LocalizedText"];
            newLeitnerBox: number;
            /** Format: date-time */
            nextReviewDate: string;
        };
        AccuracyDataPoint: {
            /** Format: date */
            date: string;
            /** Format: double */
            accuracy: number;
        };
        RecentExamSummary: {
            /** Format: uuid */
            examId: string;
            score: number;
            passed: boolean;
            /** Format: date-time */
            completedAt: string;
        };
        DashboardDto: {
            totalQuestionsPracticed: number;
            totalExamsTaken: number;
            /** Format: double */
            averageExamScore: number;
            currentStreak: number;
            dueForReview: number;
            questionsAnsweredToday: number;
            /** Format: double */
            examPassRate: number;
            recentExams: components["schemas"]["RecentExamSummary"][];
            accuracyOverTime: components["schemas"]["AccuracyDataPoint"][];
        };
        CategoryPerformanceDto: {
            /** Format: uuid */
            categoryId: string;
            categoryName: components["schemas"]["LocalizedText"];
            totalAttempts: number;
            correctAttempts: number;
            /** Format: double */
            accuracy: number;
            questionsInCategory: number;
            questionsPracticed: number;
        };
        PlanDto: {
            /** Format: uuid */
            id: string;
            name: components["schemas"]["LocalizedText"];
            description: components["schemas"]["LocalizedText"];
            /** Format: int64 */
            priceInTiyins: number;
            durationDays: number;
            features: components["schemas"]["LocalizedText"][];
        };
        CreateSubscriptionRequest: {
            /** Format: uuid */
            planId: string;
            /** @enum {string} */
            paymentProvider: "payme" | "click";
        };
        SubscriptionResultDto: {
            /** Format: uuid */
            subscriptionId: string;
            paymentUrl: string;
            /** @enum {string} */
            status: "none" | "active" | "expired" | "cancelled";
        };
        SubscriptionStatusDto: {
            /** @enum {string} */
            status: "none" | "active" | "expired" | "cancelled";
            planName?: components["schemas"]["LocalizedText"];
            /** Format: date-time */
            expiresAt?: string | null;
            autoRenew?: boolean;
        };
        AdminDashboardDto: {
            totalUsers: number;
            activeSubscriptions: number;
            totalQuestions: number;
            activeQuestions: number;
            totalExamsToday: number;
            /**
             * Format: int64
             * @description Amount in tiyins
             */
            revenueThisMonth: number;
        };
        BulkImportResultDto: {
            totalRows: number;
            imported: number;
            updated: number;
            skipped: number;
            errors: {
                row: number;
                column: string;
                error: string;
            }[];
        };
        AdminPlanDto: {
            /** Format: uuid */
            id: string;
            name: components["schemas"]["LocalizedText"];
            description: components["schemas"]["LocalizedText"];
            /** Format: int64 */
            priceInTiyins: number;
            durationDays: number;
            features: components["schemas"]["LocalizedText"][];
            isActive: boolean;
            subscriberCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        CreatePlanRequest: {
            name: components["schemas"]["LocalizedText"];
            description: components["schemas"]["LocalizedText"];
            /** Format: int64 */
            priceInTiyins: number;
            durationDays: number;
            features: components["schemas"]["LocalizedText"][];
            isActive: boolean;
        };
        UpdatePlanRequest: {
            name: components["schemas"]["LocalizedText"];
            description: components["schemas"]["LocalizedText"];
            /** Format: int64 */
            priceInTiyins: number;
            durationDays: number;
            features: components["schemas"]["LocalizedText"][];
            isActive: boolean;
        };
        PaymentTransactionDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            userName: string | null;
            userPhone: string;
            /** @enum {string} */
            provider: "payme" | "click";
            providerTransactionId?: string | null;
            /**
             * Format: int64
             * @description Amount in tiyins
             */
            amount: number;
            /** @default UZS */
            currency: string;
            /** @enum {string} */
            status: "pending" | "completed" | "failed" | "refunded";
            planName?: components["schemas"]["LocalizedText"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt?: string | null;
        };
        ProviderRevenue: {
            provider: string;
            /** Format: int64 */
            revenue: number;
            count: number;
        };
        PeriodRevenue: {
            date: string;
            /** Format: int64 */
            revenue: number;
            count: number;
        };
        PlanRevenue: {
            planName: string;
            /** Format: int64 */
            revenue: number;
            count: number;
        };
        RevenueReportDto: {
            /**
             * Format: int64
             * @description Amount in tiyins
             */
            totalRevenue: number;
            transactionCount: number;
            /** Format: int64 */
            averageTransaction: number;
            byProvider: components["schemas"]["ProviderRevenue"][];
            byPeriod: components["schemas"]["PeriodRevenue"][];
            byPlan: components["schemas"]["PlanRevenue"][];
        };
        ExamPoolRuleDto: {
            /** Format: uuid */
            categoryId: string;
            categoryName?: components["schemas"]["LocalizedText"];
            /** @enum {integer|null} */
            difficulty?: 1 | 2 | 3 | null;
            questionCount: number;
        };
        ExamTemplateDto: {
            /** Format: uuid */
            id: string;
            title: components["schemas"]["LocalizedText"];
            totalQuestions: number;
            passingScore: number;
            timeLimitMinutes: number;
            isActive: boolean;
            poolRules: components["schemas"]["ExamPoolRuleDto"][];
        };
        CreateExamTemplateRequest: {
            title: components["schemas"]["LocalizedText"];
            totalQuestions: number;
            passingScore: number;
            timeLimitMinutes: number;
            isActive: boolean;
            poolRules: {
                /** Format: uuid */
                categoryId: string;
                /** @enum {integer|null} */
                difficulty?: 1 | 2 | 3 | null;
                questionCount: number;
            }[];
        };
        AuditLogDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            userName: string | null;
            /** @enum {string} */
            action: "Create" | "Update" | "Delete" | "StatusChange" | "Login" | "Export";
            /** @enum {string} */
            entityType: "Question" | "Plan" | "User" | "ExamTemplate" | "Setting" | "Announcement";
            entityId: string | null;
            changes?: {
                field: string;
                oldValue?: string | null;
                newValue?: string | null;
            }[];
            ipAddress?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        SystemSettingDto: {
            key: string;
            value: string;
            description: string | null;
            updatedBy?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        UserDetailDto: {
            /** Format: uuid */
            id: string;
            phoneNumber: string | null;
            firstName?: string | null;
            lastName?: string | null;
            /** @enum {string} */
            role: "user" | "admin";
            /** @enum {string|null} */
            authProvider?: "phone" | "telegram" | null;
            /** @enum {string} */
            preferredLanguage?: "uz" | "uzLatin" | "ru";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastActiveAt?: string | null;
            subscription?: {
                /** @enum {string} */
                status?: "none" | "active" | "expired" | "cancelled";
                planName?: components["schemas"]["LocalizedText"];
                /** Format: date-time */
                expiresAt?: string | null;
                autoRenew?: boolean;
            };
            stats: {
                totalExams: number;
                /** Format: double */
                avgScore: number;
                /** Format: double */
                passRate: number;
                totalQuestionsPracticed: number;
                currentStreak: number;
                dueForReview: number;
            };
            recentExams?: {
                /** Format: uuid */
                examId: string;
                score: number;
                passed: boolean;
                /** Format: date-time */
                date: string;
            }[];
            payments?: {
                /** Format: uuid */
                id: string;
                /** Format: int64 */
                amount: number;
                /** @enum {string} */
                provider: "payme" | "click";
                /** @enum {string} */
                status: "pending" | "completed" | "failed" | "refunded";
                /** Format: date-time */
                date: string;
            }[];
        };
        AnnouncementDto: {
            /** Format: uuid */
            id: string;
            title: components["schemas"]["LocalizedText"];
            content: components["schemas"]["LocalizedText"];
            /** @enum {string} */
            type: "info" | "warning" | "important";
            isActive: boolean;
            /** Format: date-time */
            startsAt?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
            createdBy?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CreateAnnouncementRequest: {
            title: components["schemas"]["LocalizedText"];
            content: components["schemas"]["LocalizedText"];
            /** @enum {string} */
            type: "info" | "warning" | "important";
            isActive: boolean;
            /** Format: date-time */
            startsAt?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sendOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendOtpRequest"];
            };
        };
        responses: {
            /** @description OTP sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["SendOtpResponse"];
                    };
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOtpRequest"];
            };
        };
        responses: {
            /** @description OTP verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
    };
    telegramLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramLoginRequest"];
            };
        };
        responses: {
            /** @description Telegram login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Token refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["UserDto"];
                    };
                };
            };
        };
    };
    getCategories: {
        parameters: {
            query?: {
                lang?: "uz" | "uzLatin" | "ru";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category tree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["CategoryTreeDto"][];
                    };
                };
            };
        };
    };
    getQuestions: {
        parameters: {
            query?: {
                categoryId?: string;
                difficulty?: 1 | 2 | 3;
                ticketNumber?: number;
                lang?: "uz" | "uzLatin" | "ru";
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated questions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: {
                            items?: components["schemas"]["QuestionDto"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
            };
        };
    };
    getTicketsList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tickets with question counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["TicketDto"][];
                    };
                };
            };
        };
    };
    getQuestionsByTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Questions for a specific ticket */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["QuestionDto"][];
                    };
                };
            };
        };
    };
    startExam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartExamRequest"];
            };
        };
        responses: {
            /** @description Exam started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ExamSessionDto"];
                    };
                };
            };
        };
    };
    startTicketExam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ticketNumber: number;
                };
            };
        };
        responses: {
            /** @description Ticket exam started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ExamSessionDto"];
                    };
                };
            };
        };
    };
    startMarathon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Marathon started (all questions, no timer) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ExamSessionDto"];
                    };
                };
            };
        };
    };
    submitExamAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerRequest"];
            };
        };
        responses: {
            /** @description Answer recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["SubmitAnswerResponse"];
                    };
                };
            };
        };
    };
    completeExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ExamResultDto"];
                    };
                };
            };
        };
    };
    getExamSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ExamSessionDto"];
                    };
                };
            };
        };
    };
    getExamHistory: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: {
                            items?: components["schemas"]["ExamHistoryItemDto"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
            };
        };
    };
    getPracticeSession: {
        parameters: {
            query?: {
                categoryId?: string;
                batchSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Practice session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["PracticeSessionDto"];
                    };
                };
            };
        };
    };
    submitPracticeAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitPracticeAnswerRequest"];
            };
        };
        responses: {
            /** @description Practice answer result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["PracticeAnswerResultDto"];
                    };
                };
            };
        };
    };
    getUserDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User dashboard */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["DashboardDto"];
                    };
                };
            };
        };
    };
    getCategoryPerformance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category performance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["CategoryPerformanceDto"][];
                    };
                };
            };
        };
    };
    getPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available plans */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["PlanDto"][];
                    };
                };
            };
        };
    };
    createSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Subscription created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["SubscriptionResultDto"];
                    };
                };
            };
        };
    };
    getSubscriptionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["SubscriptionStatusDto"];
                    };
                };
            };
        };
    };
    cancelSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    paymeWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description JSON-RPC 2.0 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    clickWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Click webhook response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    getActiveAnnouncements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active announcements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["AnnouncementDto"][];
                    };
                };
            };
        };
    };
    adminGetQuestions: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                search?: string;
                categoryId?: string;
                isActive?: boolean;
                difficulty?: 1 | 2 | 3;
                ticketNumber?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated admin questions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: {
                            items?: components["schemas"]["QuestionDto"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
            };
        };
    };
    adminCreateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: uuid */
                    categoryId: string;
                    /** @description Uzbek Cyrillic */
                    textUz: string;
                    /** @description Uzbek Latin */
                    textUzLatin: string;
                    /** @description Russian */
                    textRu: string;
                    explanationUz?: string;
                    explanationUzLatin?: string;
                    explanationRu?: string;
                    /** @enum {integer} */
                    difficulty: 1 | 2 | 3;
                    ticketNumber: number;
                    /** @enum {string} */
                    licenseCategory: "AB" | "CD" | "BOTH";
                    /** @default true */
                    isActive?: boolean;
                    /** Format: binary */
                    questionImage?: string;
                    "options[0].textUz"?: string;
                    "options[0].textUzLatin"?: string;
                    "options[0].textRu"?: string;
                    "options[0].isCorrect"?: boolean;
                    /** Format: binary */
                    "options[0].image"?: string;
                    "options[1].textUz"?: string;
                    "options[1].textUzLatin"?: string;
                    "options[1].textRu"?: string;
                    "options[1].isCorrect"?: boolean;
                    /** Format: binary */
                    "options[1].image"?: string;
                    "options[2].textUz"?: string;
                    "options[2].textUzLatin"?: string;
                    "options[2].textRu"?: string;
                    "options[2].isCorrect"?: boolean;
                    /** Format: binary */
                    "options[2].image"?: string;
                    "options[3].textUz"?: string;
                    "options[3].textUzLatin"?: string;
                    "options[3].textRu"?: string;
                    "options[3].isCorrect"?: boolean;
                    /** Format: binary */
                    "options[3].image"?: string;
                    "options[4].textUz"?: string;
                    "options[4].textUzLatin"?: string;
                    "options[4].textRu"?: string;
                    "options[4].isCorrect"?: boolean;
                    /** Format: binary */
                    "options[4].image"?: string;
                    "options[5].textUz"?: string;
                    "options[5].textUzLatin"?: string;
                    "options[5].textRu"?: string;
                    "options[5].isCorrect"?: boolean;
                    /** Format: binary */
                    "options[5].image"?: string;
                };
            };
        };
        responses: {
            /** @description Question created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["QuestionDto"];
                    };
                };
            };
        };
    };
    adminUpdateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: uuid */
                    categoryId?: string;
                    /** @description Uzbek Cyrillic */
                    textUz?: string;
                    /** @description Uzbek Latin */
                    textUzLatin?: string;
                    /** @description Russian */
                    textRu?: string;
                    explanationUz?: string;
                    explanationUzLatin?: string;
                    explanationRu?: string;
                    /** @enum {integer} */
                    difficulty?: 1 | 2 | 3;
                    ticketNumber?: number;
                    /** @enum {string} */
                    licenseCategory?: "AB" | "CD" | "BOTH";
                    isActive?: boolean;
                    keepQuestionImage?: boolean;
                    /** Format: binary */
                    questionImage?: string;
                    "keepOptionImages[0]"?: boolean;
                    "keepOptionImages[1]"?: boolean;
                    "keepOptionImages[2]"?: boolean;
                    "keepOptionImages[3]"?: boolean;
                    "keepOptionImages[4]"?: boolean;
                    "keepOptionImages[5]"?: boolean;
                    "options[0].textUz"?: string;
                    "options[0].textUzLatin"?: string;
                    "options[0].textRu"?: string;
                    "options[0].isCorrect"?: boolean;
                    /** Format: binary */
                    "options[0].image"?: string;
                    "options[1].textUz"?: string;
                    "options[1].textUzLatin"?: string;
                    "options[1].textRu"?: string;
                    "options[1].isCorrect"?: boolean;
                    /** Format: binary */
                    "options[1].image"?: string;
                    "options[2].textUz"?: string;
                    "options[2].textUzLatin"?: string;
                    "options[2].textRu"?: string;
                    "options[2].isCorrect"?: boolean;
                    /** Format: binary */
                    "options[2].image"?: string;
                    "options[3].textUz"?: string;
                    "options[3].textUzLatin"?: string;
                    "options[3].textRu"?: string;
                    "options[3].isCorrect"?: boolean;
                    /** Format: binary */
                    "options[3].image"?: string;
                    "options[4].textUz"?: string;
                    "options[4].textUzLatin"?: string;
                    "options[4].textRu"?: string;
                    "options[4].isCorrect"?: boolean;
                    /** Format: binary */
                    "options[4].image"?: string;
                    "options[5].textUz"?: string;
                    "options[5].textUzLatin"?: string;
                    "options[5].textRu"?: string;
                    "options[5].isCorrect"?: boolean;
                    /** Format: binary */
                    "options[5].image"?: string;
                };
            };
        };
        responses: {
            /** @description Question updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["QuestionDto"];
                    };
                };
            };
        };
    };
    adminSoftDeleteQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Question soft-deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminPermanentDeleteQuestion: {
        parameters: {
            query: {
                confirm: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Question permanently deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminToggleQuestionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    isActive: boolean;
                };
            };
        };
        responses: {
            /** @description Status toggled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminBulkToggleStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    questionIds: string[];
                    isActive: boolean;
                };
            };
        };
        responses: {
            /** @description Bulk status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: {
                            updatedCount?: number;
                        };
                    };
                };
            };
        };
    };
    adminBulkImportQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    excelFile: string;
                    /** Format: binary */
                    imagesZip?: string;
                    /**
                     * @default skip
                     * @enum {string}
                     */
                    duplicateStrategy?: "skip" | "update" | "error";
                };
            };
        };
        responses: {
            /** @description Import result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["BulkImportResultDto"];
                    };
                };
            };
        };
    };
    adminExportTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Excel template */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    adminGetDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin dashboard */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["AdminDashboardDto"];
                    };
                };
            };
        };
    };
    adminGetPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin plans list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["AdminPlanDto"][];
                    };
                };
            };
        };
    };
    adminCreatePlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanRequest"];
            };
        };
        responses: {
            /** @description Plan created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["AdminPlanDto"];
                    };
                };
            };
        };
    };
    adminUpdatePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlanRequest"];
            };
        };
        responses: {
            /** @description Plan updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["AdminPlanDto"];
                    };
                };
            };
        };
    };
    adminTogglePlanStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    isActive: boolean;
                };
            };
        };
        responses: {
            /** @description Plan status toggled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminGetTransactions: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                userId?: string;
                provider?: "payme" | "click";
                status?: "pending" | "completed" | "failed" | "refunded";
                dateFrom?: string;
                dateTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated transactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: {
                            items?: components["schemas"]["PaymentTransactionDto"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
            };
        };
    };
    adminGetRevenue: {
        parameters: {
            query?: {
                period?: "daily" | "weekly" | "monthly";
                dateFrom?: string;
                dateTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revenue report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["RevenueReportDto"];
                    };
                };
            };
        };
    };
    adminExportRevenue: {
        parameters: {
            query?: {
                dateFrom?: string;
                dateTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revenue export Excel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    adminGetExamTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ExamTemplateDto"][];
                    };
                };
            };
        };
    };
    adminCreateExamTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExamTemplateRequest"];
            };
        };
        responses: {
            /** @description Template created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ExamTemplateDto"];
                    };
                };
            };
        };
    };
    adminUpdateExamTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExamTemplateRequest"];
            };
        };
        responses: {
            /** @description Template updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ExamTemplateDto"];
                    };
                };
            };
        };
    };
    adminExportUsers: {
        parameters: {
            query?: {
                dateFrom?: string;
                dateTo?: string;
                subscriptionStatus?: "none" | "active" | "expired" | "cancelled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users export Excel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    adminExportExams: {
        parameters: {
            query?: {
                dateFrom?: string;
                dateTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exams export Excel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    adminExportQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Questions export Excel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    adminGetAuditLogs: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                userId?: string;
                action?: "Create" | "Update" | "Delete" | "StatusChange" | "Login" | "Export";
                entityType?: "Question" | "Plan" | "User" | "ExamTemplate" | "Setting" | "Announcement";
                dateFrom?: string;
                dateTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated audit logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: {
                            items?: components["schemas"]["AuditLogDto"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
            };
        };
    };
    adminGetSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["SystemSettingDto"][];
                    };
                };
            };
        };
    };
    adminUpdateSetting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    value: string;
                };
            };
        };
        responses: {
            /** @description Setting updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["SystemSettingDto"];
                    };
                };
            };
        };
    };
    adminGetUsers: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                search?: string;
                subscriptionStatus?: "none" | "active" | "expired" | "cancelled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: {
                            items?: components["schemas"]["UserDto"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
            };
        };
    };
    adminGetUserDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["UserDetailDto"];
                    };
                };
            };
        };
    };
    adminUpdateUserRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    role: "user" | "admin";
                };
            };
        };
        responses: {
            /** @description Role updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminUpdateUserStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    isBlocked: boolean;
                };
            };
        };
        responses: {
            /** @description User status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminGetAnnouncements: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                isActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated announcements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: {
                            items?: components["schemas"]["AnnouncementDto"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
            };
        };
    };
    adminCreateAnnouncement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnnouncementRequest"];
            };
        };
        responses: {
            /** @description Announcement created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["AnnouncementDto"];
                    };
                };
            };
        };
    };
    adminUpdateAnnouncement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnnouncementRequest"];
            };
        };
        responses: {
            /** @description Announcement updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["AnnouncementDto"];
                    };
                };
            };
        };
    };
    adminDeleteAnnouncement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Announcement deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
